server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/black_note
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 10   # 最大连接数
          max-idle: 10  # 最大空闲连接数
          min-idle: 1  # 最小空闲连接数
          time-between-eviction-runs: 10s  # 每隔多久检查一次连接池中的连接状态。
  # 新增 RabbitMQ 配置
  rabbitmq:
    host: 127.0.0.1          # RabbitMQ 服务器地址 (本地测试用 127.0.0.1)
    port: 5672               # 消息通信端口 (注意不是 15672 管理端口)
    username: guest          # 默认用户名
    password: guest          # 默认密码
    virtual-host: /          # 虚拟主机，默认为 /
    listener:
      simple:
        prefetch: 1          # 每次只抓取一条消息，防止消费者压力过大
        acknowledge-mode: auto # 自动确认消息已接收
  jackson:
    default-property-inclusion: non_null   # json自动忽略null值，不需要序列化

mybatis-plus:
  type-aliases-package: com.syr.entity    # 扫描包
minio:
  endpoint: http://localhost:9000    # MinIO服务地址
  access-key: minioadmin             # 账号
  secret-key: minioadmin             # 密码
  bucket: syr                # 存储桶名称

# SpringDoc OpenAPI 配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
logging:
  level:
    com.syr: debug
